apiVersion: apps/v1
kind: Deployment
metadata:
  name: alibi-perfeito-crud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crud
  template:
    metadata:
      labels:
        app: crud
    spec:
      containers:
        - name: alibi-perfeito-crud
          image: rodrigo453/alibipereito-crud:v5 #v5 apontamento ip keycloak
          ports:
            - containerPort: 5001
---
apiVersion: v1
kind: Service
metadata:
  name: service-alibi-perfeito-crud  # nome alterado para seguir as regras
spec:
  selector:
    app: crud  # nome alterado para seguir as regras
  ports:
    - port: 5001
      targetPort: 5001
  type: NodePort