apiVersion: apps/v1
kind: Deployment
metadata:
  name: alibi-perfeito-crud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crud
  template:
    metadata:
      labels:
        app: crud
    spec:
      containers:
        - name: alibi-perfeito-crud
          image: rodrigo453/alibiperfeito-crud:v2
          ports:
            - containerPort: 5004
---
apiVersion: v1
kind: Service
metadata:
  name: service-alibi-perfeito-crud
spec:
  selector:
    app: crud
  ports:
    - port: 5004
      targetPort: 5004
  type: NodePort 