version: '3.8'

networks:
  alibiperfeito-network:
    driver: bridge

services:
  bastion:
    image: alpine:latest
    container_name: bastion
    command: sh # Inicia com um shell interativo
    stdin_open: true # Para permitir comandos interativos
    tty: true # Para habilitar o terminal
    ports:
      - "6060:6060" # Você pode abrir outras portas, se necessário
    networks:
      - alibiperfeito-network
