apiVersion: apps/v1
kind: Deployment
metadata:
  name: alibi-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: alibi-perfeito-api-gateway
          image: rodrigo453/alibiperfeito-apigateway:134
          ports:
            - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: service-alibi-api-gateway  # nome alterado para seguir as regras
spec:
  selector:
    app: api-gateway  # nome alterado para seguir as regras
  ports:
    - port: 8084
      targetPort: 8084
  type: NodePort