apiVersion: apps/v1
kind: Deployment
metadata:
  name: alibi-perfeito-sorry-random-no-login  # nome alterado para seguir as regras
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sorry-random-no-login  # nome alterado para seguir as regras
  template:
    metadata:
      labels:
        app: sorry-random-no-login  # nome alterado para seguir as regras
    spec:
      containers:
        - name: alibi-perfeito-sorry-random-no-login  # nome alterado para seguir as regras
          image: rodrigo453/alibiperfeito-sorryrandomnologin:v3
          ports:
            - containerPort: 30005
---
apiVersion: v1
kind: Service
metadata:
  name: service-sorry-random-no-login  # nome alterado para seguir as regras
spec:
  selector:
    app: sorry-random-no-login  # nome alterado para seguir as regras
  ports:
    - port: 30005
      targetPort: 30005
      nodePort: 30005
  type: NodePort
