apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-pv-claim
  namespace: keycloak
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: "local-path"  # O seu storageClassName correto
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      volumes:
        - name: keycloak-data-volume  # Nome do volume
          persistentVolumeClaim:
            claimName: keycloak-pv-claim  # Referência ao PVC correto
      containers:
        - name: keycloak
          image: bitnami/keycloak:latest
          env:
            - name: KEYCLOAK_ADMIN
              value: admin
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: admin
            - name: KEYCLOAK_DATABASE_HOST
              value: dpg-cu4kcvt2ng1s738j39fg-a.oregon-postgres.render.com
            - name: KEYCLOAK_DATABASE_NAME
              value: alibiperfeitodb_tfgn
            - name: KEYCLOAK_DATABASE_USER
              value: alibiperfeitouser
            - name: KEYCLOAK_DATABASE_PASSWORD
              value: 7qHsvBIJvbBU7XSTXolQJb7htXMdIA39
            - name: KEYCLOAK_DATABASE_SCHEMA
              value: keycloak
            - name: KEYCLOAK_LOGLEVEL
              value: DEBUG
            - name: KEYCLOAK_LOG_FILE
              value: /opt/keycloak/logs/keycloak.log
          ports:
            - containerPort: 9090
          volumeMounts:
            - mountPath: "/mnt/data"
              name: keycloak-data-volume
---
apiVersion: v1
kind: Service
metadata:
  name: service-keycloak
spec:
  selector:
    app: keycloak
  ports:
    - port: 9090
      targetPort: 9090
  type: NodePort
