apiVersion: apps/v1
kind: Deployment
metadata:
  name: bastion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bastion
  template:
    metadata:
      labels:
        app: bastion
    spec:
      containers:
        - name: bastion
          image: alpine:latest
          command: ["/bin/sh", "-c", "while true; do sleep 30; done;"] # Mantém o container rodando
          ports:
            - containerPort: 6060
---
apiVersion: v1
kind: Service
metadata:
  name: bastion  # nome alterado para seguir as regras
spec:
  selector:
    app: bastion  # nome alterado para seguir as regras
  ports:
    - port: 6060
      targetPort: 6060
  type: NodePort