apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-pv-volume
  labels:
    type: local
spec:
  storageClassName: keycloak
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-pv-claim
  namespace: infra
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: keycloak

