name: DeployArgo

on:
  push:
    branches:
      - "main"

jobs:
  alteraTag:
    runs-on: ubuntu-latest  # Corrigido para ubuntu-latest

    steps:
      - name: Checkout do repositório de deploy
        uses: actions/checkout@v2
        with:
          repository: "rodrigo453/AlibiPerfeito-Devops"
          token: ${{ secrets.DEPLOYMENT_REPO_ACCESS_TOKEN }} 
        
      - name: Alterar a tag no deployment.yaml
        run: |
          IMAGE_TAG=rodrigo453/alibiperfeito-apigateway:134
          sed -i "s|image: rodrigo453/alibiperfeito-apigateway:.*|image: $IMAGE_TAG|" ArgoCD/AlibiPerfeit-APIGateway/deployment.yaml  # Atualizando a tag no arquivo correto
       
      
