name: DeployArgo

on:
  workflow_call:
    inputs:
      var:
        required: true
        type: string  # Definindo a tag como input obrigatório

jobs:

  teste:
    runs-on: ubuntu-latest
    steps:
      - name: Print inputs
        run: |
          echo "input_var: ${{ inputs.var }}"
      
