name: DeployArgo

on:
 workflow_call:
    inputs:
      var:
        required: true
        type: string
      
jobs:
  alteraTag:
    runs-on: ubuntu-latest  # Corrigido para ubuntu-latest

    steps:
      - name: Checkout do repositório de deploy
        uses: actions/checkout@v2
        with:
          repository: "rodrigo453/AlibiPerfeito-APIGateway"
          token: ${{ secrets.DEPLOYMENT_REPO_ACCESS_TOKEN }} 
        
      - name: Alterar a tag no deployment.yaml
        run: |
          IMAGE_TAG=rodrigo453/alibiperfeito-apigateway:${{ inputs.var }}
          sed -i "s|image: rodrigo453/alibiperfeito-apigateway:.*|image: $IMAGE_TAG|" ./ArgoCD/AlibiPerfeit-APIGateway/deployment.yaml  # Atualizando a tag no arquivo correto

      - name: Commit updated deployment file
        run: |
          git config --global user.email "rodrigochicora.azevedo@gmail.com"
          git config --global user.name "rodrigo453"
          git add ArgoCD/AlibiPerfeit-APIGateway/deployment.yaml
          git commit -m "Update image version to ${{ inputs.var }}"
          git push origin main  # Certifique-se de usar o token de acesso, se necessário
       
      
