name: DeployArgo

on:
  workflow_call:
    inputs:
      var:
        required: true
        type: string

jobs:
  alteraTag:
    runs-on: ubuntu:latest
    env:
      Tag: ${{ inputs.var }}  # A variável 'Tag' recebe o parâmetro

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2
        
      - name: Alterar a tag no deployment.yaml
        run: |
          sed -i "s|image: rodrigo453/alibiperfeito-apigateway:.*|image: rodrigo453/alibiperfeito-apigateway:${{ env.Tag }}|" ./main.yaml
